<testsuites name="results">
  <testsuite name="all" package="all">
    <property name="random_seed" value="1724488639" />
    <testcase name="run_test_write_001" classname="test_axi_crossbar_wr" file="/Users/fatimafarooq/Desktop/axi_LLM/venv/lib/python3.12/site-packages/cocotb/regression.py" lineno="731" time="0.012559175491333008" sim_time_ns="0.001" ratio_time="0.07962306129809975">
      <failure message="Test failed with RANDOM_SEED=1724488639" />
    </testcase>
    <testcase name="run_test_write_002" classname="test_axi_crossbar_wr" file="/Users/fatimafarooq/Desktop/axi_LLM/venv/lib/python3.12/site-packages/cocotb/regression.py" lineno="731" time="0.0034890174865722656" sim_time_ns="0.001" ratio_time="0.286613639469728">
      <failure message="Test failed with RANDOM_SEED=1724488639" />
    </testcase>
    <testcase name="run_test_write_003" classname="test_axi_crossbar_wr" file="/Users/fatimafarooq/Desktop/axi_LLM/venv/lib/python3.12/site-packages/cocotb/regression.py" lineno="731" time="0.0035970211029052734" sim_time_ns="0.001" ratio_time="0.27800782130310864">
      <failure message="Test failed with RANDOM_SEED=1724488639" />
    </testcase>
    <testcase name="run_test_write_004" classname="test_axi_crossbar_wr" file="/Users/fatimafarooq/Desktop/axi_LLM/venv/lib/python3.12/site-packages/cocotb/regression.py" lineno="731" time="0.0032379627227783203" sim_time_ns="0.001" ratio_time="0.3088361681761284">
      <failure message="Test failed with RANDOM_SEED=1724488639" />
    </testcase>
  </testsuite>
</testsuites>
